apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: kafka-workshop-modulo3-lab1
build:
  artifacts:
  - image: inventory-service
    docker:
      dockerfile: Dockerfile
      buildArgs:
        MODULE: 'saga-choreography'
        SERVICE: 'inventory-service'
  - image: order-service
    docker:
      dockerfile: Dockerfile
      buildArgs:
        MODULE: 'saga-choreography'
        SERVICE: 'order-service'
  - image: payment-service
    docker:
      dockerfile: Dockerfile
      buildArgs:
        MODULE: 'saga-choreography'
        SERVICE: 'payment-service'
deploy:
  kubectl:
    manifests:
    - k8s/101-app.yaml
