server:
  port: 8080
spring.cloud.stream:
  function:
    definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-event
      group: order-service
    paymentEventConsumer-in-0:
      destination: payment-event
      group: order-service
    inventoryEventConsumer-in-0:
      destination: inventory-event
      group: order-service
spring.kafka.bootstrapServers: https://lab-kafka-bootstrap:9092
